version: '3'

services:
  app-server:
    build: ./docker
    image: laravel-site
    depends_on:
      - mysql
    volumes:
      - ./:/application

  mysql:
    image: mysql:5.7
    ports:
      - "13310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel-site
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application
    depends_on:
      - app-server
